[package]
name = "opa"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmtime = "0.31.0"
anyhow = "1.0"
thiserror = "1.0"